source("gdp_data.R")
world_gdp <-read.csv("world_gdp.csv")
india_gdp <-subset(gdp_data,select = c(Financial.Year,Gross.Domestic.Product..in.Rs..Cr..at.2004.05.Prices))
names(india_gdp) <- c("Year","India_GDP")
world_gdp <- subset(world_gdp,select=c("Year","X.int...."))
names(world_gdp) <- c("Year","World_GDP")
india_gdp$Year = c(1951:2011)
world_gdp<-subset(world_gdp,Year >1950)
world_gdp<-subset(world_gdp,Year <2012)
india_gdp$India_GDP <- india_gdp$India_GDP/min(india_gdp$India_GDP)
world_gdp$World_GDP <- world_gdp$World_GDP/min(world_gdp$World_GDP)
india_vs_world <- merge(india_gdp, world_gdp, by = "Year")
india_vs_world <- melt(india_vs_world,id.vars = "Year")
names(india_vs_world) <- c("Year","Entity","Growth")

global_gdp <- read.csv("real-gdp-per-capita-PWT.csv")
names(global_gdp) <- c("Entity","Code","Year","Real_GDP")
politics <- read.csv("political-regime-updated2016.csv")
countries <- subset(politics,Year == 1950)
countries <- subset(countries,  Political.Regime..OWID.based.on.Polity.IV.and.Wimmer...Min...Score. >5)
countries <- subset(countries,select = -Year)
names(countries) <- c("Country","Code","Democracy_score")
plot_countries <- filter(global_gdp,Code %in% countries$Code)
#ggplot(plot_countries,aes(x = Year,y= Real_GDP))+geom_line(aes(color = Entity,group = Entity))
