source("gdp_data.R")
library(broom)
mod <- lm (Agriculture ~ Agriculture_allied_services, gdp_percent)
print("The Corelation factor is")
print(cor(gdp_percent$Agriculture, gdp_percent$Agriculture_allied_services))
new_data <- augment(mod)
print("The relationship is linear")
# data_to_predict <- data.frame(c(Agri_value))
# colnames(data_to_predict) <- c("Agriculture_allied_services")
# predict(new_data,data_to_predict)
# .hat value in new_data gives Leverage and .cooksd gives the influence (cook's Coefficent)...